- name : Un-install everything
  hosts: db_and_webserver1
  tasks:


      - name: "Stop DB Sevice"
        service:
          name: mysql
          state: stopped  
        become: yes  


      - name: Un-Install Mysql DB servers
        apt: name="{{ item }}" state=absent
        with_items:
          - mysql-server
          - mysql-client
        become: yes 
          
      - name: Un-Install Web server
        apt: name={{ item }} state=absent
        with_items:
          - python
          - python-setuptools
          - python-dev
          - build-essential 
          - python-pip 
          - python-mysqldb
        become: yes
        
